## Import Libraries

In [1]:
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np

## Senteces

In [2]:
sen = [ 'the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'I am good developer',
       'understand the meaning of words',
       'your videos are good',
       'the new good videos are easy to understand']

In [3]:
sen

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am good developer',
 'understand the meaning of words',
 'your videos are good',
 'the new good videos are easy to understand']

In [4]:
# Vocabulary size
voc_size = 10000

In [5]:
onehot_represent = [one_hot(words,voc_size) for words in sen]

In [6]:
onehot_represent

[[4547, 1776, 7653, 2123],
 [4547, 1776, 7653, 7549],
 [4547, 7621, 7653, 2443],
 [8505, 7547, 5515, 3284, 1436],
 [8505, 7547, 3284, 1710],
 [6325, 4547, 1294, 7653, 7760],
 [9206, 2539, 2201, 3284],
 [4547, 1469, 3284, 2539, 2201, 8960, 5459, 6325]]

## Word Embedding Representation

In [7]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential

In [8]:
sen_length = 8
embeded_doc = pad_sequences(onehot_represent,padding='pre',maxlen=sen_length)

In [9]:
print(embeded_doc)

[[   0    0    0    0 4547 1776 7653 2123]
 [   0    0    0    0 4547 1776 7653 7549]
 [   0    0    0    0 4547 7621 7653 2443]
 [   0    0    0 8505 7547 5515 3284 1436]
 [   0    0    0    0 8505 7547 3284 1710]
 [   0    0    0 6325 4547 1294 7653 7760]
 [   0    0    0    0 9206 2539 2201 3284]
 [4547 1469 3284 2539 2201 8960 5459 6325]]


In [10]:
dim = 15

In [11]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sen_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embeded_doc)

1/1 [==============================] - 0s 74ms/step


array([[[-0.01304047, -0.01723119,  0.01308015,  0.01619184,
         -0.03334504, -0.01328788, -0.04139606,  0.04500303,
          0.00660553, -0.02949324],
        [-0.01304047, -0.01723119,  0.01308015,  0.01619184,
         -0.03334504, -0.01328788, -0.04139606,  0.04500303,
          0.00660553, -0.02949324],
        [-0.01304047, -0.01723119,  0.01308015,  0.01619184,
         -0.03334504, -0.01328788, -0.04139606,  0.04500303,
          0.00660553, -0.02949324],
        [-0.01304047, -0.01723119,  0.01308015,  0.01619184,
         -0.03334504, -0.01328788, -0.04139606,  0.04500303,
          0.00660553, -0.02949324],
        [ 0.03723026,  0.01291751,  0.02628309,  0.01317606,
         -0.00172261, -0.04465249,  0.02005079,  0.02458913,
         -0.00671167, -0.01605827],
        [-0.0413764 ,  0.0196304 ,  0.04130722, -0.00327884,
          0.0106569 ,  0.0030541 , -0.00093664,  0.04235894,
         -0.03876355, -0.04173542],
        [ 0.0010367 ,  0.02500138,  0.00126354,  0.0

In [14]:
embeded_doc[0]

array([   0,    0,    0,    0, 4547, 1776, 7653, 2123])

In [15]:
model.predict(embeded_doc[0])

1/1 [==============================] - 0s 37ms/step


array([[-0.01304047, -0.01723119,  0.01308015,  0.01619184, -0.03334504,
        -0.01328788, -0.04139606,  0.04500303,  0.00660553, -0.02949324],
       [-0.01304047, -0.01723119,  0.01308015,  0.01619184, -0.03334504,
        -0.01328788, -0.04139606,  0.04500303,  0.00660553, -0.02949324],
       [-0.01304047, -0.01723119,  0.01308015,  0.01619184, -0.03334504,
        -0.01328788, -0.04139606,  0.04500303,  0.00660553, -0.02949324],
       [-0.01304047, -0.01723119,  0.01308015,  0.01619184, -0.03334504,
        -0.01328788, -0.04139606,  0.04500303,  0.00660553, -0.02949324],
       [ 0.03723026,  0.01291751,  0.02628309,  0.01317606, -0.00172261,
        -0.04465249,  0.02005079,  0.02458913, -0.00671167, -0.01605827],
       [-0.0413764 ,  0.0196304 ,  0.04130722, -0.00327884,  0.0106569 ,
         0.0030541 , -0.00093664,  0.04235894, -0.03876355, -0.04173542],
       [ 0.0010367 ,  0.02500138,  0.00126354,  0.03893441,  0.03167354,
         0.04266765,  0.0105911 ,  0.03647398

**Here we can notice each value is represent using 10 vector**